### ISSUE TITLE
Suggestion: Better Themed Scrollbars?

### ISSUE THREAD

**Issue by CarJem** [samuelthomas2774/nxapi#78]
Chromium Default Scrollbars don't really fit the overall app... I have made a css mockup of a more fitting change

```css
/* width */
::-webkit-scrollbar {
    height: 6px;
    width: 6px;
    
}

/* Track */
::-webkit-scrollbar-track {
    background: transparent;
    margin: 6px;
}

/* Handle */
::-webkit-scrollbar-thumb {
    background: #888;
    border: 6px;
    border-radius: 6px;
    
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
    background: #555;
}
```

![image](https://github.com/samuelthomas2774/nxapi/assets/18092668/8da838d0-bd17-474d-8d6e-3ffcaa832a01)
